### ISSUE TITLE
Support ogg

### ISSUE THREAD

**Issue by pyrotechnick** [kolber/audiojs#1]
"It plays mp3s. No ogg. Because, lets be honest, in the real world, no one really exports ogg files."

That's no reason not to support ogg when it makes sense. Not supporting ogg just for the sake of it, or assuming nobody prefers or uses oggs is rather foolish.

**Comment by Zetaphor** [comment]
Closing this issue in an effort to clean things up. This can be re-visited in the future, but is not on the current roadmap.
