### ISSUE TITLE
Error loading music.mp3

### ISSUE THREAD

**Issue by nirajmchauhan** [kolber/audiojs#101]
I just found that if the browser is having a download manager installed then the player always shows Error loading song.mp3

I am using IDM as download manager, if I turn that off then the player plays well but if its enabled then in all browsers(IE9, Chrome, firefox, safari) I get the same message. 

Error loading song.mp3

Can you help why this is happening?

**Comment by Zetaphor** [comment]
Unable to reproduce with latest IDM and browser releases
