### ISSUE TITLE
Android Bug

### ISSUE THREAD

**Issue by realdannys** [kolber/audiojs#107]
I thought I was going mad, our player had developed lots of bugs on Android in the last few days (default browser not Chrome) sometimes tracks wouldn't play, if they did they'd take a while to start, the counter doesn't show total time for track which means the progression bar doesn't work either. Skipping tracks often skips two and doesn't load the one it lands on.

It basically doesn't work anymore. I've tested this on both a real device and the simulator and both ICS and Jellybean with our player, the fork of the player from the person we bought it off and with your demo player off the site, all display the same bug.

The strangest thing of all is that his DEFINITELY didn't happen a week or so ago as I went around all the stores checking our website out on different devices and tried the default Android browser a few times, it also worked fine on my S2 test device - but there is definitely a bug now. How this could have happened when code hasn't changed I've no idea. Input?

**Comment by Zetaphor** [comment]
Please provide a code sample, along with information on which Android/Browser/Webview you're using. Closing until further information is provided.
