### ISSUE TITLE
Using a self-closing <audio> tag breaks player

### ISSUE THREAD

**Issue by leighmarble** [kolber/audiojs#146]
Perhaps this is more a suggestion to revise the "Usage" guide, which shows the audio tag being used in a self-closing format:

    <audio src="/mp3/juicy.mp3" preload="auto" />

After quite a bit of trial and error, I realized that was the source of problems I was having with it.

See http://www.refusesoftware.com/test_audiojs.php for an example - there should be 3 audio players on that page, but since I did the second audio tag as self-closing, the 3rd player doesn't appear. And the 2nd player's controls aren't displaying correctly. 

Tested on both Firefox 26.0 and Safari 5.1 on OS X, and also Safari mobile on iOS 7.

**Comment by Zetaphor** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
