### ISSUE TITLE
not working on iOS after load&play

### ISSUE THREAD

**Issue by jleed** [kolber/audiojs#154]
if render html audio tag with url on mp3 stream and call createAll(); we getting sound ok, bug if render empty html audio tag and then via js load(); & play(); mp3 stream (I'm using socket.io for getting session url on mp3) browser seems like cannot load something, player always display loading/buffering. 

        socket.emit('play', id, function(res){
			if (!player) player = audiojs.create();
          	player[0].load(res.audio);
          	player[0].play();
	    });

what's I am doing wrong?

**Comment by Zetaphor** [comment]
Please provide a proper test case to reproduce
