### ISSUE TITLE
http://kolber.github.io/audiojs/ demo not working in mobile Safari

### ISSUE THREAD

**Issue by jamiearthur** [kolber/audiojs#163]
We are experiencing issues getting audiojs to work in mobile Safari, it appears the same issues happen with the demo on the developers website as shown below. 

![screen shot 2014-04-16 at 5 49 34 pm](https://cloud.githubusercontent.com/assets/250361/2716459/ebaa80b4-c52a-11e3-9d06-efa9f1b06a84.png)

**Comment by Mdpproduction** [comment]
doesn't work on android

**Comment by elribonazo** [comment]
Anybody can append any logfiles or errors to help developers? On mac with a device / simulator and MAC's Safari you can see the error log.

But anyway I've tested this player on lots of devices and it works perfectly.

**Comment by Zetaphor** [comment]
Unable to reproduce, please provide logfiles and I will investigate.
