### ISSUE TITLE
how add play all button?

### ISSUE THREAD

**Issue by immortalcain** [kolber/audiojs#170]
$('#playall-bt').click(function(e) {
          e.preventDefault();
          audio.load(first);
          audio.play();
          $('ol li:first-child').addClass('playing').siblings().removeClass('playing');
trackEnded: function() {
            var next = $('ol li.playing').next();
            if (!next.length) next = $('ol li').first();
            next.addClass('playing').siblings().removeClass('playing');
            audio.load($('a', next).attr('data-src'));
            audio.play();
          }
        });

**Comment by Zetaphor** [comment]
These types of questions are best suited for StackOverflow, please keep github issues on the topic of the libraries functions.
