### ISSUE TITLE
URL crashes iOS Safari

### ISSUE THREAD

**Issue by Andrew-Barton** [kolber/audiojs#172]
Hi,

Does anyone have any idea why the following URL crashes mobile Safari.

http://test:test@rs2.stream24.org:8470/stream

The web page is here:

http://www.witteringmediasuite.co.uk/Customers/audiojs/

The 'loading' animation shows for about 80 seconds and then Safari crashes back to the home screen.

Hope someone can help.
Regards,
Andrew

**Comment by Zetaphor** [comment]
Unable to reproduce and test url is no longer valid. Please provide a working test case.
