### ISSUE TITLE
audio.js player controls appear on top of existing <audio> player.

### ISSUE THREAD

**Issue by quinncomendant** [kolber/audiojs#180]
I've included the audio.js file:
```
<script src="/audiojs/audio.js"></script>
```

I have an html5 audio tag:
```
<audio controls preload="metadata">
    <source src="/file.mp3" type="audio/mpeg">
</audio>
```

I'm executing audio.js like this:
```
$(document).ready(function() {
    var as = audiojs.createAll();        
});
```

It works, however the original default html5 player remains displayed, as in this screenshot:

![screenshot](http://i.imgur.com/1h0lEvU.png)

**Comment by twxia** [comment]
The play button's margin have some problem.
![screenshot from 2015-06-03 13 06 31](https://cloud.githubusercontent.com/assets/2068895/7953042/64c22522-09f1-11e5-8625-d488417d791d.png)

**Comment by Zetaphor** [comment]
What browser release has this been verified on?

**Comment by Zetaphor** [comment]
Not reproducible in the latest release. Please re-open this issue if it still occurs, with a JSBin containing a set of reproducible steps. Check this element's CONTRIBUTING.md for an example.
