### ISSUE TITLE
Not working with tinymce editor

### ISSUE THREAD

**Issue by shwetalanet** [kolber/audiojs#189]
I used your audiojs with my blog detail page (http://prntscr.com/73y6h7) and it works fine but it can't work with my frontend blog editor page.

Frontend blog editor page have tinymce editor (http://prntscr.com/73y6nr). I means that is not working inside editor.

All helps are appreciated!

Thanks,
Shweta

**Comment by Zetaphor** [comment]
This question is best directed to Stackoverflow, as it is outside of the scope of this library. Please keep github issues on the function of the library.
