### ISSUE TITLE
add package.json

### ISSUE THREAD

**Issue by maruilian11** [kolber/audiojs#192]
would you please consider adding package.json so that we can add your lib on https://cdnjs.com.
thank you very much!
https://github.com/cdnjs/cdnjs/issues/5566

**Comment by buschschwick** [comment]
+1 to this and making an npm package.

**Comment by Zetaphor** [comment]
Will publish an npm package when I get some free time

**Comment by SohKai** [comment]
@Zetaphor Just wanted to ping you in case you've forgotten about this :).

**Comment by schmod** [comment]
I'd also like to see this published to NPM!
