### ISSUE TITLE
add tags for each version

### ISSUE THREAD

**Issue by maruilian11** [kolber/audiojs#193]
would you please consider adding tags for each version so that we can add your lib on https://cdnjs.com/ with **git auto-update**.
thank you very much!
https://github.com/cdnjs/cdnjs/issues/5566

**Comment by EndenDragon** [comment]
I've made a pull request for it to be added!

**Comment by Zetaphor** [comment]
@maruilian11 Tags have been added and will be maintained from here forward. Thanks for the suggestion!

**Comment by maruilian11** [comment]
thank you very much! i will add this lib asap :+1:

**Comment by EndenDragon** [comment]
idk if i did it right https://github.com/cdnjs/cdnjs/pull/7230

**Comment by maruilian11** [comment]
@EndenDragon thank you!
