### ISSUE TITLE
How can I see the title of what's playing?

### ISSUE THREAD

**Issue by friendshipmn** [kolber/audiojs#199]
I would like it to say, "Now Playing: Song Title" - above the player.  Is this possible?

**Comment by rawsonkara** [comment]
edit the innerHtml of this node (assuming you are using standard markup)
http://prntscr.com/9q1156

will set the view like this
http://prntscr.com/9q11jd

the jquery selector for my example is
$("#audiojs_wrapper0 .scrubber .progress").html("Some Song Title");

I Would recommend setting this inside the createPlayer Event which you declare in your config settings when calling create()

**Comment by Zetaphor** [comment]
These types of questions are best suited for StackOverflow. Please keep github issues pertinent to the actual functions of the library.
