### ISSUE TITLE
Stop other players on a site when clicking play

### ISSUE THREAD

**Issue by seppentoni** [kolber/audiojs#201]
Is it possible to somehow stop the current player on a page when clicking on another play button?

I have four players on a page. So when one Is playing and I click on another player the current player is stoppet and the other one starts.

**Comment by seppentoni** [comment]
I guess thats the same issue as: https://github.com/kolber/audiojs/pull/133
How do I implement this "single" functionality? Cant's finding anything in the doc's

**Comment by tjbladez** [comment]
It is. All instances are available globally. You can scan you page to find selectors for instances you want to stop and stop them via global reference.

**Comment by tjbladez** [comment]
something as simple as this could help you to get instance
```
getAudiojsInstance = function(element){
 return audiojs.instances[element.attr("id").replace("_wrapper","")];
}
```

**Comment by seppentoni** [comment]
Hmm. I dont get along with js very well.

If I have this markup:
```
<div class="audioPlayer"><audio src="{{ asset.url }}" preload="none" /></audio></div>
<div class="audioPlayer"><audio src="{{ asset.url }}" preload="none" /></audio></div>
<div class="audioPlayer"><audio src="{{ asset.url }}" preload="none" /></audio></div>
```
and this js:
```
$(document).ready(function() {

	audiojs.events.ready(function() {
	  var as = audiojs.createAll();
	});
	getAudiojsInstance = function(element){
	 return audiojs.instances[element.attr("id").replace("_wrapper","")];
	});

});
```

How would I alter your code in order to work?

**Comment by tjbladez** [comment]
Ok, you should start by understanding what happens here, @seppentoni.

* When createAll() runs for each for your <audio> tags it will create audiojs instance 
* Updates dom to populate with audiojs wrapper (by default div with class `audiojs`)
* Each of those audiojs wrappers get unique id (again default is audiojs_wrapper0,audiojs_wrapper1,audiojs_wrapper2 etc).
* Notice that each of those numbers map to the names of instances in the instances collection. So replace does a string substitution to move extra "_wrapper" string to pull names of audiojs instances

Lets say you need to stop all instances on the page and you are using jquery. Then you code to pause on the page could look like this:
```
$('.audiojs').each(function(idx, el){
  var name  = $(el).attr('id').replace("_wrapper", "");
  audiojs.instances[name].pause();
});
```
Now, everyone situation is different so depending on if you are using a single page application or loading each pages separately there are easier ways of handling it (like simply iteration over each instance and pausing it), however in general if you ever in situation where you need to grab just one instance of the audiojs aforementioned logic applies.

**Comment by seppentoni** [comment]
Hmmm. That doesn't work.
There is now a live exmaple: http://beer-music.ch/medien

What would be the selector? The play button? The parent element. I don't get it.

The code here is:

```
$(document).ready(function() {

  audiojs.events.ready(function() {
    var as = audiojs.createAll();
  });

  $('.play-pause').find('.audiojs').each(function(idx, el){
	  var name  = $(el).attr('id').replace("_wrapper", "");
	  audiojs.instances[name].pause();
	});
  
	
});
```

**Comment by tjbladez** [comment]
Ok, two things:
 * you should not be pausing instances on ready
 * because of the find your selector must be one of the parents of the audiojs. In your case it is class `.audioPlayer`.
 * So the ideal code for you that pauses all other instances except for one clicked is actually easier since it is not a frontend application and not loading audio dynamically. Here it is:
```
$(document).ready(function() {
  audiojs.events.ready(function() {
    var as = audiojs.createAll();
  });
  $('.play').on('click', function(event){
    for (var prop in audiojs.instances) {
      audiojs.instances[prop].pause();
    }
    return true;
  })
});
```

**Comment by seppentoni** [comment]
Wow. you're fast. This is not working. What am I doing wrong. Is the jquery Version to high?

**Comment by tjbladez** [comment]
@seppentoni for the sake of not polluting this project we can take this conversation off this issue  - reach out to me via `tjbladez` twitter or skype. 
Overall I looked at your minified js file, it still has old code (where you use replace "_wrapper"). 
Once you update to the latest I sent (i just confirmed it works by running it on your site manually): 
```
  $('.play').on('click', function(event){
    for (var prop in audiojs.instances) {
      audiojs.instances[prop].pause();
    }
    return true;
  });
```

**Comment by seppentoni** [comment]
Okay. We figured out the problem. The above code didn't work because the audiojs events werent ready when click is run.

For future reference.
If you have multiple players on your page without any special dynamic fluff
and you need all your instances to stop when you click on another play button:

```
audiojs.events.ready(function() {
  var as = audiojs.createAll();
  $('.play').on('click', function(event){
    for (var prop in audiojs.instances) {
      audiojs.instances[prop].pause();
    }
    return true;
  });
});
```
