### ISSUE TITLE
audio.min.js has not been updated since 2012

### ISSUE THREAD

**Issue by andrewringler** [kolber/audiojs#217]
I had been using audio.min.js without realizing that it hasn't been updated since 2012 and is out of sync with audio.js

**Comment by Zetaphor** [comment]
Wow, lacking on my part eh?

I'm currently insanely busy with work and home ownership, so I can't promise I'll get to this before next week. That said, I'd accept a PR ;-)

**Comment by andrewringler** [comment]
Aaah. Will do. PR it is.

Andrew
