### ISSUE TITLE
Chrome - Error loading

### ISSUE THREAD

**Issue by tsquillario** [kolber/audiojs#37]
If I leave the player open for a while, playing a song or not the player eventually says "Error loading: "[url of mp3]". I can still play/pause as well as change songs via some buttons I have ties to the javascript events. Even if i switch tracks it still has this error BUT will switch the song and continue to play.

Only seems to happen in Chrome. Any ideas?

**Comment by OneTXxL** [comment]
I encounter a problem with this player: "error loading" in chrome have a solution please, thank you

**Comment by Zetaphor** [comment]
This issue appears to have been resolved in the latest Chrome release for desktop and mobile. Please let me know if this problem still occurs.
