### ISSUE TITLE
DOM Exception: INDEX_SIZE_ERR (1)

### ISSUE THREAD

**Issue by magnetica** [kolber/audiojs#38]
i have this error:
Errore: DOM Exception: INDEX_SIZE_ERR (1)

if you have a big file (es 20MB) and you clic on the progress bar, when is loaded a different chunk, if you click again on a previus loaded chunk you see this error

cheers

**Comment by Zetaphor** [comment]
Please provide a code sample to reproduce the issue. I will re-open this issue once the issue is reproducible.
