### ISSUE TITLE
Support m4a/AAC

### ISSUE THREAD

**Issue by rafikk** [kolber/audiojs#41]
I'm planning to use audiojs to play track previews from the iTunes API. An example file is the following: http://a3.mzstatic.com/us/r1000/120/Music/e4/67/7e/mzi.apuygpon.aac.p.m4a

Any plans to support this filetype? And if not, any pointer on how to go about modifying the AS file to allow it?

Thanks,
Rafik

**Comment by Zetaphor** [comment]
This is not on the current roadmap, but a pull request is welcome.
