### ISSUE TITLE
multiple playlists

### ISSUE THREAD

**Issue by darije** [kolber/audiojs#47]
is it possible (and how) to create multiple playlists on one page?
tnx

**Comment by markvador** [comment]
Hi thanks a lot it was so helpful for me. In this example the script would return tu play the first track of the current album. How could I change this so after the last song of my album it would lauch the first one of the next album ? (in other words  select the first <li> of the next <ol> in the trackEnded function. )

**Comment by Izoniz** [comment]
Hello! If you need it in separate ol you should find next ol everytime. 
If you have 2 albums you can add class="album" in ol and comment this line: 
```javascript
if (!next.length) next = $('ol.album li').first();
```
And add this code on it's place.
```javascript
            if (!next.length) {   
				$('ol li.playing').parent().removeClass('album');
				next = $('ol.album li').first();
				$('ol li.playing').parent().addClass('album');
			}
```
You also need to comment 2 lines in this code:
```javascript
        // Load in a track on click
        $('ol li').click(function(e) {
          e.preventDefault();
          //$('ol').removeClass('album');
          //$(this).parent().addClass('album');
          $('ol li').removeClass('playing');
          $(this).addClass('playing');//.siblings().removeClass('playing');
          audio.load($('a', this).attr('data-src'));
          audio.play();
        });
```
And you need to change code in // Keyboard shortcuts section.
This is the full code:
```javascript
$(function() { 
        // Setup the player to autoplay the next track
        var a = audiojs.createAll({
          trackEnded: function() {
            var next = $('ol li.playing').next();
            if (!next.length) {   
				$('ol li.playing').parent().removeClass('album');
				next = $('ol.album li').first();
				$('ol li.playing').parent().addClass('album');
			}
			
			//if (!next.length) next = $('ol.next li').first();
            $('ol li').removeClass('playing');
            next.addClass('playing');//.siblings().removeClass('playing');
            audio.load($('a', next).attr('data-src'));
            audio.play();
          }
        });

     // Load in the first track
        var audio = a[0];
            first = $('ol a').attr('data-src');
        $('ol').first().addClass('album');
        $('ol li').first().addClass('playing');
        audio.load(first);

        // Load in a track on click
        $('ol li').click(function(e) {
          e.preventDefault();
          //$('ol').removeClass('album');
          //$(this).parent().addClass('album');
          $('ol li').removeClass('playing');
          $(this).addClass('playing');//.siblings().removeClass('playing');
          audio.load($('a', this).attr('data-src'));
          audio.play();
        });

        // Keyboard shortcuts
        $(document).keydown(function(e) {
          var unicode = e.charCode ? e.charCode : e.keyCode;
             // right arrow
          if (unicode == 39) {
            var next = $('li.playing').next();
            if (!next.length) {   
				$('ol li.playing').parent().removeClass('album');
				next = $('ol.album li').first();
				$('ol li.playing').parent().addClass('album');
			}
            next.click();
            // back arrow
          } else if (unicode == 37) {
            var prev = $('li.playing').prev();
            if (!prev.length) {   
				$('ol li.playing').parent().removeClass('album');
				prev = $('ol.album li').last();
				$('ol li.playing').parent().addClass('album');
			}
            prev.click();
            // spacebar
          } else if (unicode == 32) {
            audio.playPause();
          }
        })
      });
```

But it's not working in 3 or more albums on the page. I just stuck with how to get next ol. If you find the solution it can be much easy to modify this code for playing unlimited albums.

**Comment by markvador** [comment]
Thanks a lot ! But indeed i have a lot of albums so it won't work for my purpose .. i didn't manage to select the next ol but i don't know the jquery langage. I had a simpler idea, putting all the tracks in a single album (ol). the problem is that i put some html code between the albums (to put the album title and a picture) but when the script jump to the first track of the next album it reads that title line and get an undefined result so the playing stops .. if i put only the title with no html tag that works .. Maybe it wouldn't be complex to adjust the trackEnded function to prevent that but i don't know how to do that ...

**Comment by Izoniz** [comment]
Hello. I'll see on weekends how to fix it.

**Comment by markvador** [comment]
Hello thank you that's great !

**Comment by lijiahui** [comment]
Hello.Thanks to your javascript, i successfully set up my website.But i found some problems that i unable to solve.
First is the player usually Failed to load on the mobile phone,but when you click the playlist,it can play,but still showing "ERROR LOADING".
The second is when i played the last song,the player showing Error loading: "undefined",and can`t get back to the first song.This is acceptable,but when you click the playlist ,the error message still showing,and music playing also.So if i want to adjust scrubber,i have to refresh the pages first.
Looking forward to your reply

**Comment by Zetaphor** [comment]
This conversation is best suited for StackOverflow

**Comment by Izoniz** [comment]
Hello! Sorry for so long answer.
My student made some changes and now it's working as you need. Don't forget to change data-src to your files.
[audiojs_albums.zip](https://github.com/kolber/audiojs/files/311559/audiojs_albums.zip)
