### ISSUE TITLE
Songs fail to play on FF - Stored on server

### ISSUE THREAD

**Issue by MrFirthy** [kolber/audiojs#53]
Hey all,

I've been looking at all of the other issues but none of them seem to properly relate to my issue. The audio JS is working brilliantly in Chrome and Safari, but Firefox and Opera are just failing to even load the song. Everything is online so no problems are being caused due to it all being stored locally. The player loads fine in FF and Opera, and when I tried to put the URL of the song used in your demos, it worked absolutely fine, so it seems to just be my own song. However, no errors appear to be thrown up =/

Any help on this would be greatly appreciated.

Many Thanks,

Ashley

**Comment by Zetaphor** [comment]
Please provide a code sample to reproduce. I will reopen this issue once the problem can be demonstrated.
