### ISSUE TITLE
Playlist src tag

### ISSUE THREAD

**Issue by carlosalas** [kolber/audiojs#59]
I've a playlist and I've created a "span" tag pointing the audio source but for some reason when I click on any tag into the playlist (eg. "h2" or "a" tags) the audio is playing. I've changed the "a" source tag for a "span" tag because I though that because I have others "a" tags this would be cause an error but it doesn't, in any case it do the same.
Also if I try to give a class to the audio source tag the player don't work.

Do you know why this is happening?

ul
 li
  div
   h2
   span src-data
   a
   a

Thank you.

**Comment by Zetaphor** [comment]
These types of questions are best directed to StackOverflow, also you did not provide a testable code sample.
