### ISSUE TITLE
Problem with Android 2.3.6

### ISSUE THREAD

**Issue by tomweiss123** [kolber/audiojs#63]
I implemented audio.js and it works great in every browser except on my Android 2.3.6 phone.  The play/pause image does not display properly.  The progress bar does not work properly.  Has anyone reported this problem?  Has anyone come up with a solution?  I have spent a lot of time getting audio.js customized and do not want to have to try to find another audio player that works for Android.  Thanks!

**Comment by Zetaphor** [comment]
Unable to reproduce in an Android VM. Please let me know if this is still an issue
