### ISSUE TITLE
Problem in Android 2.3.5

### ISSUE THREAD

**Issue by romamatusevich** [kolber/audiojs#73]
There is a problem in Android 2.3.5 HTC Desire HD. progressClass box run to fast. Found that problem with value of the this.duration - it`s always by default - 1.

**Comment by olgaSkobeleva** [comment]
Same issue on Android 4.4.2 (Samsung Galaxy Note 2): progress bar gets width of 100% instantly and it's impossible to navigate through audio file.

**Comment by Zetaphor** [comment]
Unable to reproduce on the same device using Chrome 48. Please provide either a test case or a device/OS/browser version to reproduce
