### ISSUE TITLE
Cannot play the 5th song

### ISSUE THREAD

**Issue by christophrumpel** [kolber/audiojs#75]
Hi,

this is very strange. I got an audiojs playlist on http://www.christophtraxler.com/media. Everythings works great, except of the the 5th song on the playlist. On chrome the player gets hidden when i click this song. On FF the song is just not playing and i get this console error: "uncaught exception: Error in Actionscript. Use a try/catch block to find error."
I have tried to change the order of the files, but it is always the 5th song. Anyone an idea?
best regards 
christoph

**Comment by Zetaphor** [comment]
Unable to reproduce this issue in Chrome and FF. Please let me know if this is still a problem.
