### ISSUE TITLE
Workaround broken preload support in Google Chome

### ISSUE THREAD

**Issue by buckett** [kolber/audiojs#8]
At the moment preload support is broken in Google Chrome.

http://code.google.com/p/chromium/issues/detail?id=16482

I wondered if it would be possible to workaround this issue by removing the <audio> tag when the page was ready and then when the user clicks play adding back the audio tag.

**Comment by Zetaphor** [comment]
Appears to be fixed in current Chrome (48). Closing issue, let me know if this is still a problem
